// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXsykP4lFO0vjJeqBViJG7iEf6xoh2Jm4',
    appId: '1:942242204558:web:fef8c175fe795eae8732df',
    messagingSenderId: '942242204558',
    projectId: 'my-finance-2e8ce',
    authDomain: 'my-finance-2e8ce.firebaseapp.com',
    storageBucket: 'my-finance-2e8ce.appspot.com',
    measurementId: 'G-19NRRGN99M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU5T-G_oEvPVHpkfjQOCNXZw0aW5S_6Ck',
    appId: '1:942242204558:android:c041e58afdfaad908732df',
    messagingSenderId: '942242204558',
    projectId: 'my-finance-2e8ce',
    storageBucket: 'my-finance-2e8ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_TH7Yw00Nh-aHmzEoIaPRsIt2iFDAdB0',
    appId: '1:942242204558:ios:c613b2f5f7d923518732df',
    messagingSenderId: '942242204558',
    projectId: 'my-finance-2e8ce',
    storageBucket: 'my-finance-2e8ce.appspot.com',
    iosClientId: '942242204558-b74r1g2htd5a7k7mfdsuo04rmkk46n5f.apps.googleusercontent.com',
    iosBundleId: 'com.financeapp.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_TH7Yw00Nh-aHmzEoIaPRsIt2iFDAdB0',
    appId: '1:942242204558:ios:c613b2f5f7d923518732df',
    messagingSenderId: '942242204558',
    projectId: 'my-finance-2e8ce',
    storageBucket: 'my-finance-2e8ce.appspot.com',
    iosClientId: '942242204558-b74r1g2htd5a7k7mfdsuo04rmkk46n5f.apps.googleusercontent.com',
    iosBundleId: 'com.financeapp.app',
  );
}
